networks:
  proxy:
    name: goat

services:
  rabbitmq:
    image: rabbitmq:4.0.3-management
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      proxy:

  redis:
    image: redis:7.4.1-alpine
    networks:
      proxy:

  # geoapi:
  #   image: ghcr.io/plan4better/goat/geoapi:latest
  #   ports:
  #     - 8100:8000
  #   networks:
  #     proxy:

  # core:
  #   image: ghcr.io/plan4better/goat/core:latest
  #   ports:
  #     - 8200:8000
  #   networks:
  #     proxy:

  # routing:
  #   image: ghcr.io/plan4better/goat/routing:latest
  #   ports:
  #     - 8300:6000
  #   networks:
  #     proxy:

  # web:
  #   image: ghcr.io/plan4better/goat/web:latest
  #   ports:
  #     - 8080:3000
  #   networks:
  #     proxy:

  # docs:
  #   image: ghcr.io/plan4better/goat/docs:latest
  #   ports:
  #     - 8081:80
  #   networks:
  #     proxy:

  # storybook:
  #   image: ghcr.io/plan4better/goat/storybook:latest
  #   ports:
  #     - 8082:80
  #   networks:
  #     proxy:
