---
name: Docker Build and Push
on:
  # REUSABLE WORKFLOW with INPUTS
  # Simplified assumptions here:
  # - can push to Docker Hub and/or GHCR (GHCR by default)
  # - optionally comments to PRs with tags + labels
  # - uses GitHub cache for buildx image layers
  # - builds PR as `pr-NUMBER`
  # - builds on default_branch as `stable-YYYYMMDD-SHA` and `latest`
  # - builds on semver tags as `latest` and the semver
  # - defaults to linux/amd64, but can multiâ€‘arch
  workflow_call:
    inputs:
      comment-enable:
        description: Create a PR comment with image tags and labels
        required: false
        default: false
        type: boolean
      context:
        description: Docker context (path) to start build from
        required: false
        type: string
      dockerhub-enable:
        description: Log into Docker Hub
        required: false
        default: false
        type: boolean
      file:
        description: Dockerfile to build, relative to context path
        required: false
        type: string
      flavor-rules:
        description: Docker metadata flavor input
        required: false
        type: string
        default: |
          latest=auto
      ghcr-enable:
        description: Log into GHCR
        required: false
        default: true
        type: boolean
      image-name:
        description: Docker image name to build
        required: true
        type: string
        default: ghcr.io/${{ github.repository }}
      platforms:
        description: Platforms to build for
        required: false
        type: string
        default: linux/amd64
      push:
        description: Push image to registry(s)
        required: false
        default: true
        type: boolean
      tag-rules:
        description: Docker metadata tag rules
        required: false
        type: string
        default: |
          type=raw,value={{sha}}
          type=ref,event=tag,priority=200
          type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }},priority=100
          type=ref,event=pr,priority=100
      target:
        description: Build stage to target
        required: false
        type: string
    secrets:
      dockerhub-username:
        description: Docker Hub username
        required: false
      dockerhub-token:
        description: Docker Hub token
        required: false

permissions:
  contents: read
  packages: write # needed to push docker image to GHCR
  pull-requests: write # needed to create/update PR comments

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            runner: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v4

      - name: ğŸ³ Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ³ Login to DockerHub
        if: inputs.dockerhub-enable
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      - name: ğŸ“¦ Login to GHCR
        if: inputs.ghcr-enable
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ³ Docker meta
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image-name }}
          flavor: ${{ inputs.flavor-rules }}
          tags: ${{ inputs.tag-rules }}

      - name: ğŸ³ Docker Build and Push (per-platform)
        id: build_image
        uses: docker/build-push-action@v5
        with:
          provenance: false
          platforms: ${{ matrix.platform }}
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          target: ${{ inputs.target }}
          builder: ${{ steps.buildx.outputs.name }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          annotations: ${{ steps.docker_meta.outputs.annotations }}
          outputs: type=image,name=${{ inputs.image-name }},push-by-digest=true,name-canonical=true,push=${{ inputs.push }}
          cache-from: type=gha,scope=build-${{ matrix.platform }}
          cache-to: type=gha,mode=max,scope=build-${{ matrix.platform }}

      - name: ğŸ“¤ Export digest
        run: |
          mkdir -p /tmp/digests/${{ matrix.platform }}
          digest="${{ steps.build_image.outputs.digest }}"
          echo "$digest" > /tmp/digests/${{ matrix.platform }}/digest.txt

      - name: ğŸ“¤ Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ matrix.platform }}
          path: /tmp/digests/${{ matrix.platform }}/*
          retention-days: 1

      # ğŸ‘‡ PR Comments
      - name: ğŸ’¬ Find existing PR comment
        if: github.event_name == 'pull_request' && inputs.comment-enable
        id: fc
        uses: peter-evans/find-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: github-actions[bot]
          body-includes: "ğŸ“¦ Docker image tags pushed"

      - name: ğŸ’¬ Create or update PR comment
        if: github.event_name == 'pull_request' && inputs.comment-enable
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: replace
          body: |
            ğŸ“¦ Docker image tags pushed:

            ```text
            ${{ steps.docker_meta.outputs.tags }}
            ```

            ğŸ· Labels added to images:

            ```text
            ${{ steps.docker_meta.outputs.labels }}
            ```

      - name: ğŸ·ï¸ Output primary image tag
        id: image-tag
        run: echo "image-tag=${{ steps.docker_meta.outputs.version }}" >> $GITHUB_OUTPUT

  merge:
    runs-on: ubuntu-latest
    needs: build
    if: inputs.push
    steps:
      - name: ğŸ“¥ Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: ğŸ³ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ğŸ³ Login to DockerHub
        if: inputs.dockerhub-enable
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      - name: ğŸ“¦ Login to GHCR
        if: inputs.ghcr-enable
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ³ Docker metadata extraction
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.image-name }}
          flavor: ${{ inputs.flavor-rules }}
          tags: ${{ inputs.tag-rules }}

      - name: ğŸ³ Create multi-arch manifest and push
        working-directory: /tmp/digests
        run: |
          docker buildx imagetools create \
            $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(find . -type f -name "digest.txt" -exec awk '{print "${{ inputs.image-name }}@"$1}' {} \;)

      - name: ğŸ³ Inspect image
        run: docker buildx imagetools inspect ${{ inputs.image-name }}:${{ steps.meta.outputs.version }}
